POST http://localhost:8080/auth/realms/fincycle/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=nest
&client_secret=c6f8e6a8-5f7d-4593-94be-4dd5e6634ac2
&grant_type=password
&username=user1@user.com
&password=123456